// Generates crates/vavilov-core/src/countries/table.rs, the countries the
// country sub-role accepts (docs/design.md, section 6), from Debian's
// iso-codes (ISO 3166-1 and 3166-3) and Natural Earth's names as
// world-atlas gives them, each at a pinned release. Run it by hand when ISO
// changes a country, with `node scripts/countries.mjs`, and commit what it
// writes; it is not part of the build or of any check.
//
// The rules:
// - a current country is named by its two- and three-letter codes, its ISO
//   name and official name, and its Natural Earth name, and shown by its
//   three-letter code;
// - a former country is named by its ISO name and four-letter code, and by
//   its two- and three-letter codes unless a current country has them; it is
//   shown by its three-letter code, or its four-letter one when a current
//   country has the three-letter one;
// - names are compared in lower case, surrounding spaces removed; a name
//   that two countries would share goes to the current one, and between two
//   current or two former countries is left out, and listed when the script
//   runs.
import fs from "node:fs";

const ISO_CODES = "https://salsa.debian.org/iso-codes-team/iso-codes/-/raw/v4.20.1/data";
const WORLD_ATLAS = "https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-50m.json";
const OUT = new URL("../crates/vavilov-core/src/countries/table.rs", import.meta.url);

async function json(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: ${String(response.status)}`);
  return response.json();
}

const current = (await json(`${ISO_CODES}/iso_3166-1.json`))["3166-1"];
const former = (await json(`${ISO_CODES}/iso_3166-3.json`))["3166-3"];
const atlas = await json(WORLD_ATLAS);

const byNumeric = new Map(current.map((country) => [country.numeric, country]));
const currentAlpha2 = new Set(current.map((country) => country.alpha_2));
const currentAlpha3 = new Set(current.map((country) => country.alpha_3));

/** Each name, in lower case, with the codes it is shown as and whether those are current. */
const names = new Map();
function add(name, code, isCurrent) {
  const key = name.trim().toLowerCase();
  if (key === "") return;
  const entry = names.get(key) ?? { current: new Set(), former: new Set() };
  (isCurrent ? entry.current : entry.former).add(code);
  names.set(key, entry);
}

for (const country of current) {
  const code = country.alpha_3;
  for (const name of [country.alpha_2, country.alpha_3, country.name, country.official_name]) {
    if (name !== undefined) add(name, code, true);
  }
}
for (const geometry of atlas.objects.countries.geometries) {
  const country = byNumeric.get(geometry.id);
  // Natural Earth's shapes with no ISO code, such as Kosovo, are not countries here.
  if (country !== undefined) add(geometry.properties.name, country.alpha_3, true);
}
for (const country of former) {
  const code = currentAlpha3.has(country.alpha_3) ? country.alpha_4 : country.alpha_3;
  add(country.name, code, false);
  add(country.alpha_4, code, false);
  if (!currentAlpha3.has(country.alpha_3)) add(country.alpha_3, code, false);
  if (!currentAlpha2.has(country.alpha_2)) add(country.alpha_2, code, false);
}

const table = [];
const leftOut = [];
for (const [name, { current: now, former: then }] of names) {
  const codes = now.size > 0 ? now : then;
  if (codes.size === 1) {
    table.push([name, [...codes][0]]);
  } else {
    leftOut.push(`${name}: ${[...codes].join(", ")}`);
  }
}
// Sorted by their UTF-8 bytes, the order of Rust's binary search on &str;
// for these names, all in the Basic Multilingual Plane, the order of
// JavaScript's comparison of strings is the same.
table.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const rust = (text) => JSON.stringify(text);
const lines = table.map(([name, code]) => `    (${rust(name)}, ${rust(code)}),`);
fs.writeFileSync(
  OUT,
  `//! Every name and code of a country the country sub-role accepts, in lower
//! case, with the code the country is shown by, sorted by name. Generated by
//! scripts/countries.mjs on ${new Date().toISOString().slice(0, 10)} from Debian's iso-codes v4.20.1
//! (ISO 3166-1 and 3166-3) and the names of Natural Earth in world-atlas
//! 2.0.2; do not edit it by hand.

/// The names, in lower case, and the code of each country.
pub(crate) const NAMES: &[(&str, &str)] = &[
${lines.join("\n")}
];
`,
);
console.log(
  `${String(table.length)} names of ${String(current.length)} current and ${String(former.length)} former countries`,
);
console.log(
  `left out, shared by two countries: ${leftOut.length === 0 ? "none" : leftOut.join("; ")}`,
);
