//! The demo table, loaded when the app starts with the cargo feature
//! `demo`, so that the windows can be tried before the import exists:
//! `npm run tauri dev -- --features demo`. It is generated by a fixed
//! formula, the same on every launch, and is never part of a release
//! build, which is made without the feature.

use std::error::Error;
use std::sync::Mutex;

use vavilov_core::{
    ColumnId, ColumnValues, Command, CommandError, NewColumn, Request, Role, Session, Stored, Table,
};

/// The number of plants of the demo table.
const NUM_PLANTS: u32 = 2_000;

/// The id of the country of origin, the active classification: the first
/// column after the names.
const COUNTRY: ColumnId = ColumnId::new(1);

/// The countries of origin, in alphabetical order as the import will give
/// their levels, each with the latitude and longitude its plants gather
/// around and the genetic cluster most of them belong to.
const COUNTRIES: [(&str, f64, f64, usize); 6] = [
    ("China", 35.0, 103.0, 3),
    ("Ethiopia", 9.0, 39.0, 2),
    ("India", 21.0, 78.0, 3),
    ("Mexico", 23.0, -102.0, 1),
    ("Peru", -10.0, -75.0, 1),
    ("Spain", 40.0, -4.0, 0),
];

/// The genetic clusters, each with its centre on the three principal
/// components.
const CLUSTERS: [(&str, [f64; 3]); 4] = [
    ("A", [-2.0, 1.0, 0.5]),
    ("B", [1.5, 2.0, -1.0]),
    ("C", [2.0, -1.5, 1.0]),
    ("D", [-1.0, -2.0, -0.5]),
];

/// The colours of the flowers, a trait.
const FLOWERS: [&str; 3] = ["purple", "white", "pink"];

const NOTES: [&str; 5] = [
    "landrace",
    "cultivar",
    "wild relative",
    "seed bank, Córdoba",
    "collected in 1998",
];

/// Loads the demo table into the session, with the country of origin as
/// the active classification.
///
/// # Errors
///
/// A poisoned lock, or the refusal of the load, which the app reports
/// before it would open with no table.
pub fn load(session: &Mutex<Session>) -> Result<(), Box<dyn Error>> {
    let mut session = session
        .lock()
        .map_err(|_| "the session's lock is poisoned")?;
    let based_on = session.revision();
    session.dispatch(Request {
        command: Command::LoadTable {
            table: table()?,
            active_classification: Some(COUNTRY),
        },
        based_on,
        sent_at: None,
    })?;
    Ok(())
}

/// The demo table: plants named `VAV-0001` and on, with the country of
/// origin, a category of countries, and a genetic cluster, a category;
/// coordinates as a latitude and a longitude, three principal components,
/// a height, a count of seeds, whether each is fertile and the colour of
/// its flower, both categories, and a note. Some values of every column
/// but the principal components are missing.
/// Each column is built by the core from its stored values and its role,
/// as the import will build them.
///
/// # Errors
///
/// The refusal of [`Table::new`], a defect of this module.
pub fn table() -> Result<Table, CommandError> {
    let mut random = Random(0x2545_F491);
    let mut names = Vec::new();
    let mut country = Vec::new();
    let mut cluster = Vec::new();
    let mut latitude = Vec::new();
    let mut longitude = Vec::new();
    let mut components: [Vec<Option<f64>>; 3] = [Vec::new(), Vec::new(), Vec::new()];
    let mut height = Vec::new();
    let mut seeds = Vec::new();
    let mut fertile = Vec::new();
    let mut flower = Vec::new();
    let mut note = Vec::new();
    for plant in 1..=NUM_PLANTS {
        names.push(format!("VAV-{plant:04}"));
        let (_, (country_name, lat, lon, usual_cluster)) = random.pick(&COUNTRIES)?;
        // Most plants of a country are in its usual cluster, the others in
        // any.
        let cluster_index = if random.chance(0.8) {
            *usual_cluster
        } else {
            random.pick(&CLUSTERS)?.0
        };
        let (cluster_name, centre) =
            CLUSTERS
                .get(cluster_index)
                .ok_or_else(|| CommandError::Defect {
                    what: format!("a demo cluster {cluster_index}"),
                })?;
        country.push(random.unless_missing(0.03, (*country_name).to_owned()));
        cluster.push(random.unless_missing(0.06, (*cluster_name).to_owned()));
        let missing_place = random.chance(0.05);
        latitude.push((!missing_place).then(|| round(lat + 4.0 * random.normal(), 4)));
        longitude.push((!missing_place).then(|| round(lon + 6.0 * random.normal(), 4)));
        for (values, mean) in components.iter_mut().zip(*centre) {
            values.push(Some(round(mean + 0.7 * random.normal(), 6)));
        }
        let plant_height = round(110.0 + 18.0 * random.normal(), 1);
        height.push(random.unless_missing(0.04, plant_height));
        let seed_count = i64::from(random.next() % 400);
        seeds.push(random.unless_missing(0.04, seed_count));
        let is_fertile = random.chance(0.85);
        fertile.push(random.unless_missing(0.03, is_fertile));
        let (_, colour) = random.pick(&FLOWERS)?;
        flower.push(random.unless_missing(0.05, (*colour).to_owned()));
        let (_, text) = random.pick(&NOTES)?;
        note.push(random.unless_missing(0.1, (*text).to_owned()));
    }
    let [pc1, pc2, pc3] = components;
    let columns = [
        ("country", Stored::Text(country), Role::Country),
        ("cluster", Stored::Text(cluster), Role::Category),
        ("latitude", Stored::Float(latitude), Role::Latitude),
        ("longitude", Stored::Float(longitude), Role::Longitude),
        ("PC1", Stored::Float(pc1), Role::Number),
        ("PC2", Stored::Float(pc2), Role::Number),
        ("PC3", Stored::Float(pc3), Role::Number),
        ("height", Stored::Float(height), Role::Number),
        ("seeds", Stored::Integer(seeds), Role::Number),
        ("fertile", Stored::Boolean(fertile), Role::Category),
        ("flower colour", Stored::Text(flower), Role::Category),
        ("note", Stored::Text(note), Role::Text),
    ];
    let columns = (1..=u32::MAX)
        .zip(columns)
        .map(|(id, (name, stored, role))| {
            Ok(NewColumn {
                name: name.to_owned(),
                values: ColumnValues::from_stored(stored, role, ColumnId::new(id), name)?,
            })
        })
        .collect::<Result<Vec<_>, CommandError>>()?;
    Table::new("IndividualID", names, columns)
}

/// `value` rounded to `decimals` places, as a file would hold it.
fn round(value: f64, decimals: i32) -> f64 {
    let scale = 10_f64.powi(decimals);
    (value * scale).round() / scale
}

/// A generator of pseudo-random numbers, Marsaglia's xorshift of 32 bits,
/// so that the table is the same on every launch and needs no crate.
struct Random(u32);

impl Random {
    fn next(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x.wrapping_shl(13);
        x ^= x.wrapping_shr(17);
        x ^= x.wrapping_shl(5);
        self.0 = x;
        x
    }

    /// A number in [0, 1).
    fn uniform(&mut self) -> f64 {
        f64::from(self.next()) / 4_294_967_296.0
    }

    /// A number of mean 0 and standard deviation 1, near enough for a
    /// demo: the sum of twelve uniforms, less 6.
    fn normal(&mut self) -> f64 {
        (0..12).map(|_| self.uniform()).sum::<f64>() - 6.0
    }

    fn chance(&mut self, probability: f64) -> bool {
        self.uniform() < probability
    }

    /// `value`, or missing with the probability given.
    fn unless_missing<T>(&mut self, probability: f64, value: T) -> Option<T> {
        (!self.chance(probability)).then_some(value)
    }

    /// An item of `items` and its index.
    fn pick<'a, T>(&mut self, items: &'a [T]) -> Result<(usize, &'a T), CommandError> {
        usize::try_from(self.next())
            .ok()
            .and_then(|value| value.checked_rem(items.len()))
            .and_then(|index| items.get(index).map(|item| (index, item)))
            .ok_or_else(|| CommandError::Defect {
                what: format!("a demo pick from {} items", items.len()),
            })
    }
}

#[cfg(test)]
mod tests;
