//! The demo table, loaded when the app starts with the cargo feature
//! `demo`, so that the windows can be tried before the import exists:
//! `npm run tauri dev -- --features demo`. It is generated by a fixed
//! formula, the same on every launch, and is never part of a release
//! build, which is made without the feature.

use std::error::Error;
use std::sync::Mutex;

use vavilov_core::{
    Categorical, Colour, ColumnId, ColumnValues, Command, CommandError, Level, LevelCode,
    NewColumn, Request, Session, Table,
};

/// The number of plants of the demo table.
const NUM_PLANTS: u32 = 2_000;

/// The id of the country of origin, the active classification: the first
/// column after the names.
const COUNTRY: ColumnId = ColumnId::new(1);

/// The countries of origin, in alphabetical order as the import will give
/// their levels, each with the latitude and longitude its plants gather
/// around and the genetic cluster most of them belong to.
const COUNTRIES: [(&str, f64, f64, usize); 6] = [
    ("China", 35.0, 103.0, 3),
    ("Ethiopia", 9.0, 39.0, 2),
    ("India", 21.0, 78.0, 3),
    ("Mexico", 23.0, -102.0, 1),
    ("Peru", -10.0, -75.0, 1),
    ("Spain", 40.0, -4.0, 0),
];

/// The genetic clusters, each with its centre on the three principal
/// components.
const CLUSTERS: [(&str, [f64; 3]); 4] = [
    ("A", [-2.0, 1.0, 0.5]),
    ("B", [1.5, 2.0, -1.0]),
    ("C", [2.0, -1.5, 1.0]),
    ("D", [-1.0, -2.0, -0.5]),
];

/// The first colours of Okabe and Ito's list, from orange, as
/// `docs/design.md`, section 5, gives them; the core's own list comes
/// with the import.
const COLOURS: [Colour; 7] = [
    rgb(0xE6, 0x9F, 0x00),
    rgb(0x56, 0xB4, 0xE9),
    rgb(0x00, 0x9E, 0x73),
    rgb(0xF0, 0xE4, 0x42),
    rgb(0x00, 0x72, 0xB2),
    rgb(0xD5, 0x5E, 0x00),
    rgb(0xCC, 0x79, 0xA7),
];

const NOTES: [&str; 5] = [
    "landrace",
    "cultivar",
    "wild relative",
    "seed bank, Córdoba",
    "",
];

const fn rgb(red: u8, green: u8, blue: u8) -> Colour {
    Colour { red, green, blue }
}

/// Loads the demo table into the session, with the country of origin as
/// the active classification.
///
/// # Errors
///
/// A poisoned lock, or the refusal of the load, which the app reports
/// before it would open with no table.
pub fn load(session: &Mutex<Session>) -> Result<(), Box<dyn Error>> {
    let mut session = session
        .lock()
        .map_err(|_| "the session's lock is poisoned")?;
    let based_on = session.revision();
    session.dispatch(Request {
        command: Command::LoadTable {
            table: table()?,
            active_classification: Some(COUNTRY),
        },
        based_on,
        sent_at: None,
    })?;
    Ok(())
}

/// The demo table: plants named `VAV-0001` and on, with two
/// classifications, coordinates, three principal components, a height, a
/// count of seeds, whether each is fertile and a note. Some values of
/// every column are missing.
///
/// # Errors
///
/// The refusal of [`Table::new`], a defect of this module.
pub fn table() -> Result<Table, CommandError> {
    let mut random = Random(0x2545_F491);
    let mut names = Vec::new();
    let mut country = Vec::new();
    let mut cluster = Vec::new();
    let mut latitude = Vec::new();
    let mut longitude = Vec::new();
    let mut components: [Vec<Option<f64>>; 3] = [Vec::new(), Vec::new(), Vec::new()];
    let mut height = Vec::new();
    let mut seeds = Vec::new();
    let mut fertile = Vec::new();
    let mut note = Vec::new();
    for plant in 1..=NUM_PLANTS {
        names.push(format!("VAV-{plant:04}"));
        let (country_code, (_, lat, lon, usual_cluster)) = random.pick(&COUNTRIES)?;
        // Most plants of a country are in its usual cluster, the others in
        // any.
        let cluster_code = if random.chance(0.8) {
            *usual_cluster
        } else {
            random.pick(&CLUSTERS)?.0
        };
        let (_, centre) = CLUSTERS
            .get(cluster_code)
            .ok_or_else(|| CommandError::Defect {
                what: format!("a demo cluster {cluster_code}"),
            })?;
        country.push(random.unless_missing(0.03, code(country_code)?));
        cluster.push(random.unless_missing(0.06, code(cluster_code)?));
        let missing_place = random.chance(0.05);
        latitude.push((!missing_place).then(|| round(lat + 4.0 * random.normal(), 4)));
        longitude.push((!missing_place).then(|| round(lon + 6.0 * random.normal(), 4)));
        for (values, mean) in components.iter_mut().zip(*centre) {
            values.push(Some(round(mean + 0.7 * random.normal(), 6)));
        }
        let plant_height = round(110.0 + 18.0 * random.normal(), 1);
        height.push(random.unless_missing(0.04, plant_height));
        let seed_count = i64::from(random.next() % 400);
        seeds.push(random.unless_missing(0.04, seed_count));
        let is_fertile = random.chance(0.85);
        fertile.push(random.unless_missing(0.03, is_fertile));
        let (_, text) = random.pick(&NOTES)?;
        note.push(random.unless_missing(0.1, (*text).to_owned()));
    }
    let [pc1, pc2, pc3] = components;
    Table::new(
        "accession",
        names,
        vec![
            categorical("country", COUNTRIES.iter().map(|c| c.0), country),
            categorical("cluster", CLUSTERS.iter().map(|c| c.0), cluster),
            column("latitude", ColumnValues::Numeric(latitude)),
            column("longitude", ColumnValues::Numeric(longitude)),
            column("PC1", ColumnValues::Numeric(pc1)),
            column("PC2", ColumnValues::Numeric(pc2)),
            column("PC3", ColumnValues::Numeric(pc3)),
            column("height", ColumnValues::Numeric(height)),
            column("seeds", ColumnValues::Integer(seeds)),
            column("fertile", ColumnValues::Boolean(fertile)),
            column("note", ColumnValues::Text(note)),
        ],
    )
}

fn column(name: &str, values: ColumnValues) -> NewColumn {
    NewColumn {
        name: name.to_owned(),
        values,
    }
}

/// A categorical column whose levels take the colours in order.
fn categorical<'a>(
    name: &str,
    levels: impl Iterator<Item = &'a str>,
    codes: Vec<Option<LevelCode>>,
) -> NewColumn {
    let levels = levels
        .zip(COLOURS.iter().cycle())
        .map(|(level, colour)| Level::new(level, *colour))
        .collect();
    column(
        name,
        ColumnValues::Categorical(Categorical::new(levels, codes)),
    )
}

fn code(index: usize) -> Result<LevelCode, CommandError> {
    u16::try_from(index)
        .map(LevelCode::new)
        .map_err(|_| CommandError::Defect {
            what: format!("a demo level {index}"),
        })
}

/// `value` rounded to `decimals` places, as a file would hold it.
fn round(value: f64, decimals: i32) -> f64 {
    let scale = 10_f64.powi(decimals);
    (value * scale).round() / scale
}

/// A generator of pseudo-random numbers, Marsaglia's xorshift of 32 bits,
/// so that the table is the same on every launch and needs no crate.
struct Random(u32);

impl Random {
    fn next(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x.wrapping_shl(13);
        x ^= x.wrapping_shr(17);
        x ^= x.wrapping_shl(5);
        self.0 = x;
        x
    }

    /// A number in [0, 1).
    fn uniform(&mut self) -> f64 {
        f64::from(self.next()) / 4_294_967_296.0
    }

    /// A number of mean 0 and standard deviation 1, near enough for a
    /// demo: the sum of twelve uniforms, less 6.
    fn normal(&mut self) -> f64 {
        (0..12).map(|_| self.uniform()).sum::<f64>() - 6.0
    }

    fn chance(&mut self, probability: f64) -> bool {
        self.uniform() < probability
    }

    /// `value`, or missing with the probability given.
    fn unless_missing<T>(&mut self, probability: f64, value: T) -> Option<T> {
        (!self.chance(probability)).then_some(value)
    }

    /// An item of `items` and its index.
    fn pick<'a, T>(&mut self, items: &'a [T]) -> Result<(usize, &'a T), CommandError> {
        usize::try_from(self.next())
            .ok()
            .and_then(|value| value.checked_rem(items.len()))
            .and_then(|index| items.get(index).map(|item| (index, item)))
            .ok_or_else(|| CommandError::Defect {
                what: format!("a demo pick from {} items", items.len()),
            })
    }
}

#[cfg(test)]
mod tests;
